#!/bin/bash


valor="$1"
dado="$2"


if [ "$valor" -gt "$dado" ]
        then
        echo "Valor invalido..."
else
        if [ "$valor" -eq "$dado" ]
                then
                        echo "Voce critou!"
                elif [ "$valor" -gt 1 ] && [ "$valor" -lt "$dado" ] ; then
                        echo "Voce acertou $1 no dado, some seus acerto e cheque a AC do oponente "
                else
                        echo "Voce teve uma falha crítica!"
        fi
fi
